# Generated by Django 3.0 on 2024-04-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageencryptiondecryption',
            name='Decrypted_Image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='imageencryptiondecryption',
            name='Encrypted_Image',
            field=models.CharField(max_length=100),
        ),
    ]
